# Generated by Django 4.1.6 on 2023-11-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_on', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('cover_page', models.ImageField(upload_to='')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_credits', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_on', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('category', models.CharField(choices=[('In Sem', 'In Sem'), ('Mid Sem', 'Mid Sem'), ('End Sem', 'End Sem'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Others', 'Others')], max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_on', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='course',
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.course'),
        ),
    ]
