# Generated by Django 4.1.6 on 2023-11-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_book_course_paper_video_delete_books_delete_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vault.course'),
            preserve_default=False,
        ),
    ]
